const faker = require("faker");

const db = require("../config/connection");
const { Appointment, User } = require("../models");

db.once("open", async () => {
  await Appointment.deleteMany({});
  await User.deleteMany({});

  // create user data
  const userData = [];

  for (let i = 0; i < 50; i += 1) {
    const username = faker.internet.userName();
    const email = faker.internet.email(username);
    const password = faker.internet.password();

    userData.push({ username, email, password });
  }

  const createdUsers = await User.collection.insertMany(userData);

  const apptData = [
    {
      day: "2021-10-23",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-23",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-10-24",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-24",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-10-25",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-25",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-10-26",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-26",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-27",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-10-28",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-28",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-29",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-10-30",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-30",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-10-31",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-11-01",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-01",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-02",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-11-03",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-03",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-04",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-11-05",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-05",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "1",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "2",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "11",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "5",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "9",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-06",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },

    {
      day: "2021-11-07",
      time: "9",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "10",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "3",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "4",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "12",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "6",
      groomer: "ally",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "5",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "10",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "11",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "1",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "12",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "3",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
    {
      day: "2021-11-07",
      time: "6",
      groomer: "bob",
      userName: userData[0].username,
      size: "small",
      serivices: "cut",
    },
  ];
  const createdaapt = await Appointment.collection.insertMany(apptData);
  console.log("all done!");
  process.exit(0);
});
