export const UPDATE_TIME = "UPDATE_TIME";
export const UPDATE_GROOMER = "UPDATE_GROOMER";
export const UPDATE_DAY = "UPDATE_DAY";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const UPDATE_SHOWMODAL = "UPDATE_SHOWMODAL";
